import os

products_code = """let products = [
    // ==================== COOKIES / BISCUITS ====================
    {
        id: 1,
        name: "Desi Ghee Cookies",
        category: "Cookies",
        price: 6.99,
        image: "assets/products/desi_ghee_cookies_fresh.png",
        images: ["assets/products/desi_ghee_cookies_fresh.png"],
        description: "Made with 100% pure desi ghee, baked to rich golden perfection with melt-in-your-mouth flavor.",
        badge: "Best Seller",
        badgeType: "popular",
        rating: 4.9,
        reviews: 312
    },
    {
        id: 2,
        name: "Cashew Biscuits",
        category: "Cookies",
        price: 7.49,
        image: "assets/products/cashew_cookies_fresh.png",
        images: ["assets/products/cashew_cookies_fresh.png"],
        description: "Loaded with rich roasted cashews and butter, delivering a satisfying crunch in every bite.",
        badge: "Popular",
        badgeType: "popular",
        rating: 4.8,
        reviews: 245
    },
    {
        id: 3,
        name: "Coconut Biscuits",
        category: "Cookies",
        price: 6.49,
        image: "assets/products/coconut_cookies_fresh.png",
        images: ["assets/products/coconut_cookies_fresh.png"],
        description: "Infused with toasted coconut flakes for a delicious tropical aroma and crisp texture.",
        badge: "Chef's Pick",
        badgeType: "new",
        rating: 4.9,
        reviews: 198
    },
    {
        id: 4,
        name: "Mango Biscuits",
        category: "Cookies",
        price: 6.99,
        image: "assets/products/mango_cookies_fresh.png",
        images: ["assets/products/mango_cookies_fresh.png"],
        description: "Subtly sweet with authentic tropical mango notes, baked to crisp perfection.",
        badge: "Special",
        badgeType: "new",
        rating: 4.7,
        reviews: 160
    },
    {
        id: 5,
        name: "Tangy Orange Biscuits",
        category: "Cookies",
        price: 6.99,
        image: "assets/products/orange_cookies_fresh.png",
        images: ["assets/products/orange_cookies_fresh.png"],
        description: "A refreshing citrus flavor paired with traditional bakery cookie goodness.",
        badge: "New",
        badgeType: "new",
        rating: 4.8,
        reviews: 142
    },
    {
        id: 6,
        name: "Royal Pista Biscuits",
        category: "Cookies",
        price: 7.99,
        image: "assets/products/pista_cookies_fresh.png",
        images: ["assets/products/pista_cookies_fresh.png"],
        description: "Generously filled with real Iranian pistachios for an elegant bakery treat.",
        badge: "Premium",
        badgeType: "popular",
        rating: 4.9,
        reviews: 280
    },
    {
        id: 7,
        name: "Flax Seed Gur Cookies",
        category: "Cookies",
        price: 7.29,
        image: "assets/products/flax_seed_gur_cookies_fresh.png",
        images: ["assets/products/flax_seed_gur_cookies_fresh.png"],
        description: "Nutritious roasted flax seeds sweetened with natural unrefined jaggery (gur).",
        badge: "Healthy",
        badgeType: "new",
        rating: 4.8,
        reviews: 175
    },
    {
        id: 8,
        name: "Ginger Gur Cookies",
        category: "Cookies",
        price: 7.29,
        image: "assets/products/ginger_gur_cookies_fresh.png",
        images: ["assets/products/ginger_gur_cookies_fresh.png"],
        description: "Infused with ginger spice and natural jaggery sweetener for a cozy tea accompaniment.",
        badge: "Seasonal",
        badgeType: "new",
        rating: 4.7,
        reviews: 130
    },
    {
        id: 9,
        name: "Gur Jaggery Cookies",
        category: "Cookies",
        price: 6.99,
        image: "assets/products/gur_jaggery_cookies_fresh.png",
        images: ["assets/products/gur_jaggery_cookies_fresh.png"],
        description: "Rich, unrefined jaggery blended with stone-ground flour and pure butter.",
        badge: "Authentic",
        badgeType: "popular",
        rating: 4.9,
        reviews: 215
    },
    {
        id: 10,
        name: "Kalounji Seeds Cookies",
        category: "Cookies",
        price: 6.99,
        image: "assets/products/kalounji_cookies_fresh.png",
        images: ["assets/products/kalounji_cookies_fresh.png"],
        description: "An aromatic savory-sweet combination featuring black nigella (kalounji) seeds.",
        badge: "Specialty",
        badgeType: "new",
        rating: 4.8,
        reviews: 140
    },
    {
        id: 11,
        name: "A-One Regular Bakery Biscuits",
        category: "Cookies",
        price: 5.99,
        image: "assets/products/a1_regular_biscuits.png",
        images: ["assets/products/a1_regular_biscuits.png"],
        description: "Classic tea-time crispy bakery biscuits cooked to perfection.",
        badge: "Classic",
        badgeType: "popular",
        rating: 4.8,
        reviews: 410
    },
    {
        id: 12,
        name: "A-One Sooji Biscuits",
        category: "Cookies",
        price: 6.29,
        image: "assets/products/a1_sooji_biscuits.png",
        images: ["assets/products/a1_sooji_biscuits.png"],
        description: "Made from premium semolina wheat for an extra crunchy texture.",
        badge: "Popular",
        badgeType: "popular",
        rating: 4.9,
        reviews: 290
    },
    {
        id: 13,
        name: "Traditional Nan Khatai",
        category: "Cookies",
        price: 6.99,
        image: "assets/products/a1_nan_khatai_biscuits.png",
        images: ["assets/products/a1_nan_khatai_biscuits.png"],
        description: "Authentic shortbread-style Indian biscuit spiced with cardamom.",
        badge: "Heritage",
        badgeType: "popular",
        rating: 5.0,
        reviews: 512
    },
    {
        id: 14,
        name: "Almond Cookies",
        category: "Cookies",
        price: 6.99,
        image: "assets/products/a1_zeera_biscuits.png",
        images: ["assets/products/a1_zeera_biscuits.png"],
        description: "Rich crunchy almond biscuits perfect with your daily tea.",
        badge: "Best Seller",
        badgeType: "popular",
        rating: 4.9,
        reviews: 388
    },
    {
        id: 15,
        name: "Whole Wheat Biscuits",
        category: "Cookies",
        price: 6.49,
        image: "assets/products/a1_whole_wheat_biscuits.png",
        images: ["assets/products/a1_whole_wheat_biscuits.png"],
        description: "100% whole grain wheat flour biscuits packed with natural fiber.",
        badge: "High Fiber",
        badgeType: "new",
        rating: 4.8,
        reviews: 195
    },
    {
        id: 16,
        name: "Family Pack Assorted Cookies Box 1",
        category: "Cookies",
        price: 12.99,
        image: "assets/products/big_box_cookies_pack_1.png",
        images: ["assets/products/big_box_cookies_pack_1.png"],
        description: "Generous family size box featuring a variety of our finest bakery cookies.",
        badge: "Value Box",
        badgeType: "popular",
        rating: 4.9,
        reviews: 260
    },
    {
        id: 17,
        name: "Grand Bakery Deluxe Selection 2",
        category: "Cookies",
        price: 13.99,
        image: "assets/products/big_box_cookies_pack_2.png",
        images: ["assets/products/big_box_cookies_pack_2.png"],
        description: "A luxury presentation box filled with premium butter & nut cookies.",
        badge: "Gift Special",
        badgeType: "new",
        rating: 5.0,
        reviews: 180
    },
    {
        id: 18,
        name: "A-One Special Gift Cookie Box 3",
        category: "Cookies",
        price: 14.49,
        image: "assets/products/big_box_cookies_pack_3.png",
        images: ["assets/products/big_box_cookies_pack_3.png"],
        description: "Handcrafted bakery cookie assortment in a special gift box packaging.",
        badge: "Gift Box",
        badgeType: "popular",
        rating: 4.9,
        reviews: 145
    },
    {
        id: 19,
        name: "Royal Bakery Assorted Box 4",
        category: "Cookies",
        price: 13.99,
        image: "assets/products/big_box_cookies_pack_4.png",
        images: ["assets/products/big_box_cookies_pack_4.png"],
        description: "A rich collection of melt-in-your-mouth bakery cookies and traditional biscuits.",
        badge: "Popular",
        badgeType: "popular",
        rating: 4.8,
        reviews: 162
    },
    {
        id: 20,
        name: "Premium Celebration Cookie Box 5",
        category: "Cookies",
        price: 14.99,
        image: "assets/products/big_box_cookies_pack_5.png",
        images: ["assets/products/big_box_cookies_pack_5.png"],
        description: "Celebration-ready bakery pack featuring roasted cashew, almond, and ghee cookies.",
        badge: "Premium",
        badgeType: "new",
        rating: 5.0,
        reviews: 198
    },
    {
        id: 21,
        name: "Festive Variety Cookie Collection 6",
        category: "Cookies",
        price: 13.49,
        image: "assets/products/big_box_cookies_pack_6.png",
        images: ["assets/products/big_box_cookies_pack_6.png"],
        description: "Festive pack of authentic baked treats prepared with traditional recipes.",
        badge: "Festive",
        badgeType: "popular",
        rating: 4.9,
        reviews: 174
    },
    {
        id: 22,
        name: "Mega Bakery Treats Box 7",
        category: "Cookies",
        price: 15.99,
        image: "assets/products/big_box_cookies_pack_7.png",
        images: ["assets/products/big_box_cookies_pack_7.png"],
        description: "Our largest assorted cookie box packed with top customer favorite bakery varieties.",
        badge: "Mega Pack",
        badgeType: "popular",
        rating: 5.0,
        reviews: 210
    },

    // ==================== CAKE RUSK ====================
    {
        id: 23,
        name: "Tutti Frutti Cake Rusk",
        category: "Cake Rusk",
        price: 5.99,
        image: "assets/products/tutti_fruity_cookies_fresh.png",
        images: ["assets/products/tutti_fruity_cookies_fresh.png"],
        description: "Rich sponge cake slices with candied fruits, double baked into sweet crunchy toast.",
        badge: "Best Seller",
        badgeType: "popular",
        rating: 5.0,
        reviews: 390
    },
    {
        id: 24,
        name: "Coconut Cake Rusk Special",
        category: "Cake Rusk",
        price: 5.99,
        image: "assets/products/coconut_cake_rusk_0.jpg",
        images: ["assets/products/coconut_cake_rusk_0.jpg"],
        description: "Twice baked cake rusks dusted with sweet toasted coconut flakes.",
        badge: "Specialty",
        badgeType: "new",
        rating: 4.9,
        reviews: 210
    },

    // ==================== TEA RUSKS ====================
    {
        id: 25,
        name: "Sooji Milk Tea Rusk",
        category: "Tea Rusks",
        price: 4.99,
        image: "assets/products/sooji_milk_rusk_fresh.png",
        images: ["assets/products/sooji_milk_rusk_fresh.png"],
        description: "Double-baked semolina rusks enriched with fresh milk. Ideal for dipping in warm chai.",
        badge: "Top Rated",
        badgeType: "popular",
        rating: 4.9,
        reviews: 420
    },
    {
        id: 26,
        name: "Sooji Milk Rusk Pack 2",
        category: "Tea Rusks",
        price: 5.29,
        image: "assets/products/sooji_milk_rusk_fresh_2.png",
        images: ["assets/products/sooji_milk_rusk_fresh_2.png"],
        description: "Extra crispy double-baked rusk crafted for a rich dunking experience.",
        badge: "Popular",
        badgeType: "popular",
        rating: 4.8,
        reviews: 310
    },
    {
        id: 27,
        name: "Whole Wheat Tea Rusk",
        category: "Tea Rusks",
        price: 4.99,
        image: "assets/products/whole_wheat_rusk_fresh.png",
        images: ["assets/products/whole_wheat_rusk_fresh.png"],
        description: "Wholesome 100% whole wheat rusks baked without refined flour.",
        badge: "Healthy Choice",
        badgeType: "new",
        rating: 4.8,
        reviews: 230
    },
    {
        id: 28,
        name: "Wheat Tea Rusk Pack 2",
        category: "Tea Rusks",
        price: 5.19,
        image: "assets/products/wheat_rusk_fresh_2.png",
        images: ["assets/products/wheat_rusk_fresh_2.png"],
        description: "Golden brown wheat rusk with mild sweetness and satisfying crunch.",
        badge: "Classic",
        badgeType: "popular",
        rating: 4.7,
        reviews: 190
    },
    {
        id: 29,
        name: "A-One Tasty Tea Rusk",
        category: "Tea Rusks",
        price: 4.49,
        image: "assets/products/tasty_tea_rusk_fresh.png",
        images: ["assets/products/tasty_tea_rusk_fresh.png"],
        description: "Everyday tea rusk baked fresh daily in our traditional ovens.",
        badge: "Best Value",
        badgeType: "popular",
        rating: 4.9,
        reviews: 480
    },
    {
        id: 30,
        name: "Tasty Tea Rusk Pack 2",
        category: "Tea Rusks",
        price: 4.79,
        image: "assets/products/tasty_tea_rusk_fresh_2.png",
        images: ["assets/products/tasty_tea_rusk_fresh_2.png"],
        description: "Crispy toast rusks seasoned with subtle cardamom aroma.",
        badge: "New",
        badgeType: "new",
        rating: 4.8,
        reviews: 165
    },

    // ==================== BHUJIYA AND OTHERS ====================
    {
        id: 31,
        name: "Classic Namak Para",
        category: "Bhujiya and others",
        price: 4.49,
        image: "assets/products/namak_para_fresh_main.png",
        images: ["assets/products/namak_para_fresh_main.png"],
        description: "Crispy savory fried ribbon bites seasoned with ajwain and black pepper.",
        badge: "Snack Favorite",
        badgeType: "popular",
        rating: 4.9,
        reviews: 370
    },
    {
        id: 32,
        name: "Golden Namak Para Pack 1",
        category: "Bhujiya and others",
        price: 4.49,
        image: "assets/products/namak_para_fresh_1.png",
        images: ["assets/products/namak_para_fresh_1.png"],
        description: "Traditional savory pastry bites, fried to perfect golden crispiness.",
        badge: "Popular",
        badgeType: "popular",
        rating: 4.8,
        reviews: 290
    },
    {
        id: 33,
        name: "Namak Para Family Pack 2",
        category: "Bhujiya and others",
        price: 6.99,
        image: "assets/products/namak_para_fresh_2.png",
        images: ["assets/products/namak_para_fresh_2.png"],
        description: "Large shareable pack of authentic savory namak para snacks.",
        badge: "Family Size",
        badgeType: "popular",
        rating: 4.9,
        reviews: 220
    },
    {
        id: 34,
        name: "Kalounji Namak Para",
        category: "Bhujiya and others",
        price: 4.79,
        image: "assets/products/kalounji_para_fresh.png",
        images: ["assets/products/kalounji_para_fresh.png"],
        description: "Savory pastry strips studded with black onion seeds (kalounji).",
        badge: "Special Flavor",
        badgeType: "new",
        rating: 4.8,
        reviews: 185
    },
    {
        id: 35,
        name: "Methi Namak Para",
        category: "Bhujiya and others",
        price: 4.79,
        image: "assets/products/methi_para_fresh.png",
        images: ["assets/products/methi_para_fresh.png"],
        description: "Infused with fragrant dried methi (fenugreek leaves) and aromatic spices.",
        badge: "Herbal Spice",
        badgeType: "new",
        rating: 4.8,
        reviews: 155
    },
    {
        id: 36,
        name: "Spicy Chatpata Para 1",
        category: "Bhujiya and others",
        price: 4.99,
        image: "assets/products/spicy_para_fresh_1.png",
        images: ["assets/products/spicy_para_fresh_1.png"],
        description: "Zesty spicy seasoning tossed over golden crispy savory bites.",
        badge: "Spicy",
        badgeType: "popular",
        rating: 4.9,
        reviews: 280
    },
    {
        id: 37,
        name: "Hot & Tangy Spicy Para 2",
        category: "Bhujiya and others",
        price: 4.99,
        image: "assets/products/spicy_para_fresh_2.png",
        images: ["assets/products/spicy_para_fresh_2.png"],
        description: "Extra spicy savory crunch snack perfect for evening tea time.",
        badge: "Hot",
        badgeType: "new",
        rating: 4.7,
        reviews: 140
    },
    {
        id: 38,
        name: "Crispy Mathri Para",
        category: "Bhujiya and others",
        price: 4.49,
        image: "assets/products/crispy_para_mathri.png",
        images: ["assets/products/crispy_para_mathri.png"],
        description: "Flaky layered mathri crackers seasoned with carom and black pepper.",
        badge: "Traditional",
        badgeType: "popular",
        rating: 4.8,
        reviews: 205
    },
    {
        id: 39,
        name: "Authentic Pani Puri Kit",
        category: "Bhujiya and others",
        price: 3.99,
        image: "assets/products/pani_puri_300_dpi_dish.png",
        images: ["assets/products/pani_puri_300_dpi_dish.png"],
        description: "Crispy hollow puri shells ready to fill with spicy mint water & chickpeas.",
        badge: "Party Pack",
        badgeType: "popular",
        rating: 4.9,
        reviews: 340
    },

    // ==================== CREAMROLLS ====================
    {
        id: 40,
        name: "Vanilla Cream Rolls",
        category: "Creamrolls",
        price: 3.99,
        image: "assets/products/cream_roll_col_1_dish.png",
        images: ["assets/products/cream_roll_col_1_dish.png"],
        description: "Flaky puff pastry horn filled with light, sweet vanilla cream.",
        badge: "Favorite",
        badgeType: "popular",
        rating: 4.8,
        reviews: 295
    },
    {
        id: 41,
        name: "Royal Cream Rolls",
        category: "Creamrolls",
        price: 3.99,
        image: "assets/products/cream_roll_col_2_dish.png",
        images: ["assets/products/cream_roll_col_2_dish.png"],
        description: "Golden flaky puff pastry rolls filled with smooth pastry cream.",
        badge: "Popular",
        badgeType: "popular",
        rating: 4.8,
        reviews: 210
    },
    {
        id: 42,
        name: "Chocolate Cream Rolls",
        category: "Creamrolls",
        price: 4.29,
        image: "assets/products/cream_roll_col_3_dish.png",
        images: ["assets/products/cream_roll_col_3_dish.png"],
        description: "Flaky pastry roll loaded with rich chocolate cream filling.",
        badge: "Choco Special",
        badgeType: "new",
        rating: 4.9,
        reviews: 260
    },
    {
        id: 43,
        name: "Strawberry Cream Rolls",
        category: "Creamrolls",
        price: 4.29,
        image: "assets/products/cream_roll_col_4_dish.png",
        images: ["assets/products/cream_roll_col_4_dish.png"],
        description: "Delicate puff pastry with fruity strawberry cream filling.",
        badge: "Fruity",
        badgeType: "new",
        rating: 4.7,
        reviews: 175
    }
]"""

with open('js/global.js', 'r', encoding='utf-8') as f:
    text = f.read()

start = text.find('let products = [')
end = text.find('];', start)

if start != -1 and end != -1:
    text = text[:start] + products_code + text[end+1:]
    with open('js/global.js', 'w', encoding='utf-8') as f:
        f.write(text)
    print("Successfully rewritten js/global.js with 100% accurate category & poster title alignment!")
else:
    print("ERROR: Could not locate products array in js/global.js")
